### ISSUE TITLE
Feature 1: User can see the list of donated items on the main page

### ISSUE THREAD

**Issue by janiicelee** [janiicelee/project-donut#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can see the list of donated items on the main page

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user goes to the main page of the app, they can view the donated items

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-14 at 12 02 22 PM](https://user-images.githubusercontent.com/57986882/163458856-0c367b1d-5fe6-4b7c-ae80-66eac5fdf390.png)
d7c9.png)

![Screen Shot 2022-04-14 at 12 01 54 PM](https://user-images.githubusercontent.com/57986882/163458912-47c6a67a-6f07-4649-9a3a-7c5450bd349a.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to the database schema that I created
- [x] Update `data.sql` to dummy data on random items

### ☁️ Server

- [x] Update `server/index.js` to get the items
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to show the items (Catalog component)
- [x] Update component to show each columns from the items table

### 🧑‍⚕️ Clean Up

- [x] ... 
- [x] ...
- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
