### ISSUE TITLE
Feature 2: User can search items by using the search bar

### ISSUE THREAD

**Issue by janiicelee** [janiicelee/project-donut#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can search a certain item that they want to find by using the search bar

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User will insert a keyword of the item that they are looking for in the search bar and the main page will show that item

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-14 at 1 23 11 PM](https://user-images.githubusercontent.com/57986882/163469553-697a3069-8fdc-40f1-bb6b-0d67f23983ec.png)
![Screen Shot 2022-04-14 at 1 23 29 PM](https://user-images.githubusercontent.com/57986882/163469596-b464b448-f2f3-4d5b-9dbd-fb5cbaf70792.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for the searchbar and itemList
- [x] Update the catalog component
- [x] Add a handleSearchChange function and setState the searchText
- [x] Make logic to filter out items depending on the searchText that user inserted to the searchbar
- [x] Add the searchbar and itemList component to the render method of the catalog component

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
