### ISSUE TITLE
Feature 3: User can donate by uploading used items

### ISSUE THREAD

**Issue by janiicelee** [janiicelee/project-donut#5]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can donate items by uploading them.

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

When the user clicks the 'Donate' button they will be redirected to the form page for uploading an item.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

![Screen Shot 2022-04-15 at 2 51 00 PM](https://user-images.githubusercontent.com/57986882/163636030-26068e82-7955-4989-98b4-420cba44b073.png)
![Screen Shot 2022-04-15 at 2 51 12 PM](https://user-images.githubusercontent.com/57986882/163636033-6d687b4d-e366-44c2-a663-ac2d6b9e273f.png)

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Create an 'uploads-middleware.js' file
- [x] Create a post method for uploading the item
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a 'donate' button on the main page
- [x] Create a form component (DonateForm)
- [x] Use hash routing to show the DonateForm when user clicks the donate button.
- [x] Make sure the upload function works when user submits the form

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
