### ISSUE TITLE
Feature 4: User can view item details

### ISSUE THREAD

**Issue by janiicelee** [janiicelee/project-donut#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can view the details of the item (donator info, content etc.)

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

Users can view item details by clicking on each item 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="616" alt="Screen Shot 2022-04-17 at 12 40 11 PM" src="https://user-images.githubusercontent.com/57986882/163729762-3ccc67a8-40f7-4b73-8af4-a20166ec9f06.png">
<img width="406" alt="Screen Shot 2022-04-17 at 12 40 51 PM" src="https://user-images.githubusercontent.com/57986882/163729789-bc2542fc-5893-4c6b-9a04-eb2bd354aefe.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### ☁️ Server

- [x] Update `server/index.js` to get detail info on the item
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component for item details (donator name, donated date, donator's location, title, content, chat with donator)
- [x] Update app component to show the item details (hash routing)

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
