### ISSUE TITLE
Feature 5: User can create an account (sign-up)

### ISSUE THREAD

**Issue by janiicelee** [janiicelee/project-donut#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can create an account

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can create an account 

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="200" alt="Screen Shot 2022-04-17 at 12 56 38 PM" src="https://user-images.githubusercontent.com/57986882/163730222-72e4c39c-dd1d-4198-8f42-deeeb71ec987.png">
<img width="590" alt="Screen Shot 2022-04-17 at 12 57 12 PM" src="https://user-images.githubusercontent.com/57986882/163730240-f7f990a0-a2f5-467c-ad2e-79aff05d1245.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server

- [x] Update `server/index.js` to make a signup method
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a Sign-up form component
- [x] Update the app component to go the signup form by using hash routing
- [x] Use geolocation and geocoding API to show user's current location

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
