### ISSUE TITLE
Feature 6: User can log-in with the account

### ISSUE THREAD

**Issue by janiicelee** [janiicelee/project-donut#8]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

User can log-in to the website

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

User can log-in using their existing account

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

<img width="203" alt="Screen Shot 2022-04-17 at 1 05 37 PM" src="https://user-images.githubusercontent.com/57986882/163730531-a854676b-a688-49ae-8a25-bc9216d2171b.png">
<img width="592" alt="Screen Shot 2022-04-17 at 1 05 21 PM" src="https://user-images.githubusercontent.com/57986882/163730532-b12c3b78-1270-469b-ad04-050577addeca.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

### 🐘 Database

- [x] Update `schema.sql` to ...
- [x] Update `data.sql` to ...

### ☁️ Server

- [x] Update `server/index.js` to make the user log-in
- [x] Test with HTTPie
- [x] Handle all errors and respond to the client

### ⚡ Client

- [x] Create a component to log-in
- [x] Update the app component to go to the log-in form by using hash routing

### 🧑‍⚕️ Clean Up

- [x] Make sure that no React state objects are being mutated.
- [x] Make sure that no event listeners are manipulating the DOM directly.
- [x] Make sure that click targets are either `<a>` or `<button>` elements.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
- [x] Remove all console logs.
- [x] Remove all commented out code.
- [x] Remove all CSS properties that have no effect.
- [x] Check all code for proper formatting and indentation.
- [x] Confirm that there are no errors in the console while using the application.
- [x] Confirm that all previous functionality still works without errors.
- [x] Confirm that the user interface looks natural on both mobile and desktop screens.
- [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
